# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.line_stepen = QtWidgets.QLineEdit(Dialog)
        self.line_stepen.setObjectName("line_stepen")
        self.gridLayout.addWidget(self.line_stepen, 1, 2, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(Dialog)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout.addWidget(self.radioButton, 2, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.line_price = QtWidgets.QLineEdit(Dialog)
        self.line_price.setObjectName("line_price")
        self.gridLayout.addWidget(self.line_price, 4, 2, 1, 1)
        self.line_description = QtWidgets.QLineEdit(Dialog)
        self.line_description.setObjectName("line_description")
        self.gridLayout.addWidget(self.line_description, 3, 2, 1, 1)
        self.line_name = QtWidgets.QLineEdit(Dialog)
        self.line_name.setObjectName("line_name")
        self.gridLayout.addWidget(self.line_name, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.line_gramm = QtWidgets.QLineEdit(Dialog)
        self.line_gramm.setObjectName("line_gramm")
        self.gridLayout.addWidget(self.line_gramm, 5, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.btn_save = QtWidgets.QPushButton(Dialog)
        self.btn_save.setObjectName("btn_save")
        self.verticalLayout.addWidget(self.btn_save, 0, QtCore.Qt.AlignHCenter)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "Описание вкуса"))
        self.label_2.setText(_translate("Dialog", "Степень обжарки"))
        self.radioButton.setText(_translate("Dialog", "да"))
        self.label_5.setText(_translate("Dialog", "Цена"))
        self.label.setText(_translate("Dialog", "Название сорта"))
        self.label_3.setText(_translate("Dialog", "Молотый?"))
        self.label_6.setText(_translate("Dialog", "Объем в граммах"))
        self.btn_save.setText(_translate("Dialog", "Сохранить"))
